# Mouse mode
setw -g mouse on

# Send Prefix
set-option -g prefix C-a
unbind-key C-a
bind-key C-a send-prefix

#setting the delay between prefix and command
set -s escape-time 5

# Set bind key to reload configuration file
bind r source-file ~/.tmux.conf \; display ​"Reloaded!"

# splitting panes with | and -
bind | split-window -h
bind - split-window -v

# count the panes from 1
set -g base-index 1
setw -g pane-base-index 1

# status bar
set -g status-right "#(pomo)"
set -g status-style "fg=#665c54"
set -g status-left-style "fg=#928374"

set -g status-bg default
set -g status-position top
set -g status-interval 1
set -g status-left ""